### ISSUE TITLE
Give better credit in changelogs

### ISSUE THREAD

**Issue by ghost** [Cytrus-RE/cytrus-re#532]
The changelog makes it seem like only you and some other dude fixed the entire bot, until you read the footer. This is why I am making this issue.

I want something like
(thing that was fixed/added) (person who added, another person who fixed it or something)

And I also want credit to Edge.

**Comment by Rexogamer** [comment]
I'm happy to figure out and provide credit for 1.4.1 and in some cases 1.4 but why Edge? I don't really recall him doing anything except hosting at first and like maybe 3 commits

EDIT: Since 1.3 all he's done is change the prefix and possibly fix one bug ![96AC237F-5E84-4DB7-914B-6587D30B9854](https://user-images.githubusercontent.com/42586271/113908746-cb039980-97ce-11eb-854f-a04db3fb643f.jpeg)

**Comment by ghost** [comment]
he helped you when you first started, you should probably give him tons of credit for that

**Comment by ghost** [comment]
plus he wanted me to tell you that so yep

**Comment by Rexogamer** [comment]
We're talking about changelogs here, specifically 1.4/1.4.1

**Comment by ghost** [comment]
still.

**Comment by ghost** [comment]
also "odyssey has left" stop saying lies lmfao you know full well you forced me out of tts

**Comment by Rexogamer** [comment]
(Side note: if you close the issue this suggests you either don't want it done or consider it resolved, so...)
